scrumlab/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from jedzonko.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', IndexView.as_view()),
    path('', HomePage.as_view()),
    path('main/', Dashboard.as_view()),
    path('recipe/<int:id>/', RecipeDetails.as_view()),
    path('recipe/add/', RecipeAdd.as_view()),
    path('recipe/modify/<int:id>/', RecipeModify.as_view()),
    path('plan/list/', Plans),
    path('plan/<int:id>/details/', PlanDetails.as_view()),
    path('plan/add/', PlanAdd.as_view()),
    path('plan/add-recipe/', PlanAddRecipe.as_view()),
    path('recipe/list/', AppRecipes),
    path('plan/modify/<int:id>/', PlanModify.as_view()),
    path('contact/', Contact.as_view()),
    path('about/', About.as_view()),
]

jedzonko/models.py
import re
from django.db import models
from enum import IntEnum
from django.template.defaultfilters import slugify


# from django.fields import EnumChoiceField


days = (
    ('pon',"Poniedziałek"),
    ('wt', "Wtorek"),
    ('śr', "Środa"),
    ('czw', "Czwartek"),
    ('pt', "Piątek"),
    ('sob', "Sobota"),
    ('nd', "Niedziela")
)
# class Days(IntEnum):
#     Poniedziałek = 1
#     Wtorek = 2
#     Środa = 3
#     Czwartek = 4
#     Piątek = 5
#     Sobota = 6
#     Niedziela = 7
#
#     @classmethod
#     def choices(cls):
#         return [(key.value, key.name) for key in cls]


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=255)
    ingredients = models.TextField()
    description = models.TextField()
    preparation = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    preparation_time = models.IntegerField()
    votes = models.IntegerField(default=0)


class DayName(models.Model):
    day_name = models.CharField(max_length=16, choices=days)
    order = models.IntegerField(unique=True)


class Plan(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created = models.DateField(auto_now_add=True)
    recipes = models.ManyToManyField(Recipe, through='RecipePlan')
    day_names = models.ManyToManyField(DayName, through='RecipePlan')


class RecipePlan(models.Model):
    meal_name = models.CharField(max_length=255)
    order = models.IntegerField()
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    day_name = models.ForeignKey(DayName, on_delete=models.CASCADE)


class Page(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Page, self).save(*args, **kwargs)

jedzonko/views.py
import string
from datetime import datetime
from django.http import HttpResponse, Http404, HttpRequest
from jedzonko.models import *
from django.shortcuts import render, redirect
from django.views import View
import random
from django.core.paginator import Paginator
from django.contrib import messages


def validation(data):
    return data != ''


def make_int(data):
    try:
        data = int(data)
    except:
        data = ''
    return data


class IndexView(View):

    def get(self, request):
        ctx = {"actual_date": datetime.now()}
        return render(request, "test.html", ctx)


class HomePage(View):
    def get(self, request):
        recipes = list(Recipe.objects.all())
        random.shuffle(recipes)
        recipes = recipes[:3]
        context = {
            'recipes': recipes
        }
        return render(request, "index.html", context)


class RecipeDetails(View):
    def get(self, request, id):
        recipe = Recipe.objects.get(pk=id)
        path = request.META.get('HTTP_REFERER')
        return render(request, 'app-recipe-details.html', {'recipe': recipe, 'id': id, 'path':path})

    def post(self, request, id):
        recipe = Recipe.objects.get(pk=id)
        like_recipe = request.POST.get("like_recipe")
        if like_recipe == "Polub przepis":
            recipe.votes += 1
        elif like_recipe == "Nie lubię przepisu":
            recipe.votes -= 1
        recipe.save()
        return HttpResponse(self.get(request, id))


class Dashboard(View):
    def get(self, request):
        number_of_recipes = Recipe.objects.count()
        number_of_plans = Plan.objects.count()
        newest_plan = Plan.objects.all().order_by('-pk')[0]
        meals = RecipePlan.objects.filter(plan=newest_plan).order_by('order')
        days = DayName.objects.all().order_by('order')
        context = {
            'number_of_recipe': number_of_recipes,
            'number_of_plan': number_of_plans,
            'newest_plan': newest_plan,
            'meals': meals,
            'days': days,
        }
        return render(request, 'dashboard.html', context=context)


class RecipeAdd(View):
    def get(self, request):
        return render(request, 'app-add-recipe.html')

    def post(self, request):
        name = request.POST.get('name')
        description = request.POST.get('description')
        preparation_time = request.POST.get('preparation_time')
        preparation = request.POST.get('preparation')
        ingredients = request.POST.get('ingredients')

        if validation(name) and validation(description) and validation(preparation) and validation(
                ingredients) and validation(make_int(preparation_time)):
            Recipe.objects.create(name=name, description=description, ingredients=ingredients,
                                  preparation_time=int(preparation_time), preparation=preparation)
            return redirect('/recipe/list/')
        info = 'Wypełnij poprawnie wszystkie pola!'
        context = {
            'name': name,
            'description': description,
            'preparation_time': preparation_time,
            'preparation': preparation,
            'ingredients': ingredients,
            'Info': info,
        }
        return render(request, 'app-add-recipe.html', context=context)


class RecipeModify(View):
    def get(self, request, id):
        try:
            recipe = Recipe.objects.get(pk=id)
            return render(request, 'app-edit-recipe.html', {'recipe': recipe})
        except:
            raise Http404

    def post(self, request, id):
        name = request.POST.get('name')
        description = request.POST.get('description')
        preparation_time = request.POST.get('preparation_time')
        preparation = request.POST.get('preparation')
        ingredients = request.POST.get('ingredients')
        if validation(name) and validation(description) and validation(preparation) and validation(
                ingredients) and validation(preparation_time):
            Recipe.objects.create(name=name, description=description, ingredients=ingredients,
                                  preparation_time=preparation_time, preparation=preparation)
            return redirect('/recipe/list/')
        messages.add_message(request, messages.INFO, "Wypełnij poprawnie wszystkie pola!")
        return redirect(f'/recipe/modify/{id}')





def Plans(request):
    if request.method == 'GET':
        app_schedules = Plan.objects.all().order_by('name')
        paginator = Paginator(app_schedules, 50)
        page = request.GET.get('page')
        schedules = paginator.get_page(page)
        return render(request, 'app-schedules.html', {'schedules': schedules})
    if request.method == 'POST':
        delete_plan_id = request.POST.get("delete_schedule_id")
        remove_plan_id = make_int(delete_plan_id)
        if validation(remove_plan_id):
            plan_to_remove = Plan.objects.get(pk=remove_plan_id)
            plan_to_remove.delete()
        return redirect('/plan/list/')





class PlanDetails(View):
    def get(self, request, id):
        plan = Plan.objects.get(pk=id)
        recipe_plan = RecipePlan.objects.filter(plan_id=id)
        meals = recipe_plan.order_by('order').order_by('day_name_id')
        days = DayName.objects.all().order_by('order')
        context = {'plan': plan,
                   'days': days,
                   'meals': meals,
                   'recipe_plan': recipe_plan}
        return render(request, 'app-details-schedules.html', context)

    def post(self, request, id):
        delete_meal_id = request.POST.get("delete_meal_id")
        remove_meal_id = make_int(delete_meal_id)
        if validation(remove_meal_id):
            meal_to_remove = RecipePlan.objects.get(pk=remove_meal_id)
            meal_to_remove.delete()
        return redirect(f'/plan/{id}/details')


class PlanAdd(View):
    def get(self, request):
        return render(request, 'app-add-schedules.html')

    def post(self, request):
        name = request.POST.get('name')
        description = request.POST.get('description')

        if validation(name) and validation(description):
            new_plan = Plan.objects.create(name=name, description=description)
            id = new_plan.id
            return redirect(f'/plan/{id}/details')
        return render(request, 'app-add-schedules.html', {'Info': 'Wypełnij poprawnie wszystkie pola!'})


class PlanAddRecipe(View):
    def get(self, request):
        days = DayName.objects.all()
        all_plans = Plan.objects.all()
        recipes = Recipe.objects.all()

        plan_id = request.GET.get('plan_id')
        if plan_id:
            plan = Plan.objects.get(pk=plan_id)
            context = {
                'plan': plan,
                'all_plans': all_plans,
                'days': days,
                'recipes': recipes,
            }
        else:
            context = {
                'all_plans': all_plans,
                'days': days,
                'recipes': recipes,
            }
        return render(request, 'app-schedules-meal-recipe.html', context=context)

    def post(self, request):
        plan_id = request.POST.get('plan_id')
        if plan_id:
            plan = Plan.objects.get(pk=plan_id)
        else:
            plan_id = request.POST.get('plan')
            plan = Plan.objects.get(pk=plan_id)

        meal_name = request.POST.get('meal_name')
        order = request.POST.get('order')

        day_id = request.POST.get('day_name_id')
        day = DayName.objects.get(pk=day_id)

        recipe_id = request.POST.get('recipe_id')
        recipe = Recipe.objects.get(pk=recipe_id)

        RecipePlan.objects.create(meal_name=meal_name, order=order, day_name=day, plan=plan,
                                  recipe=recipe)

        return redirect(f'/plan/{plan_id}/details')





def AppRecipes(request):
    if request.method == 'GET':
        app_recipes = Recipe.objects.all().order_by('-created').order_by('-votes')
        paginator = Paginator(app_recipes, 50)
        page = request.GET.get('page')
        recipes = paginator.get_page(page)
        return render(request, 'app-recipes.html', {'recipes': recipes})

    if request.method == 'POST':

        submit = request.POST.get('submit')
        if submit == 'szukaj':
            lookup = request.POST.get('q')

            if validation(lookup):
                recipes = Recipe.objects.filter(name__icontains=lookup).order_by('-created').order_by('-votes')
                return render(request, 'app-recipes.html', {'recipes': recipes})
            return redirect('/recipe/list/')
        else:
            delete_recipe_id = request.POST.get("delete_recipe_id")
            remove_recipe_id = make_int(delete_recipe_id)
            if validation(remove_recipe_id):
                recipe_to_remove = Recipe.objects.get(pk=remove_recipe_id)
                recipe_to_remove.delete()
            return redirect('/recipe/list/')


def set_recipe_data():
    for _ in range(0, 150):
        recipe = Recipe()
        letters = string.ascii_lowercase
        recipe.name = ''.join(random.choice(letters) for i in range(16))
        recipe.ingredients = ''.join(random.choice(letters) for i in range(32))
        recipe.description = ''.join(random.choice(letters) for i in range(32))
        recipe.preparation = ''.join(random.choice(letters) for i in range(32))
        recipe.preparation_time = random.randint(1, 240)
        recipe.votes = random.randint(1, 99)
        recipe.save()


def set_plan_data():
    for _ in range(0, 180):
        plan = Plan()
        letters = string.ascii_lowercase
        plan.name = ''.join(random.choice(letters) for i in range(16))
        plan.description = ''.join(random.choice(letters) for i in range(32))
        plan.save()


class PlanModify(View):
    def get(self, request, id):
        try:
            plan = Plan.objects.get(pk=id)

jedzonko/templates/__base__.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} | Zaplanuj Jedzonko</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Charmonman:400,700|Open+Sans:400,600,700&amp;subset=latin-ext"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    <header class="page-header">
        <nav class="navbar navbar-expand-lg justify-content-between">
            <a href="/" class="navbar-brand main-logo main-logo-smaller">
                Zaplanuj <span>Jedzonko</span>
            </a>
         <div class="d-flex justify-content-around">
             <h4 class="text-light mr-3">Imię</h4>
             <div class="circle-div text-center"><i class="fas fa-user icon-user"></i></div>
         </div>
        </nav>
    </header>

    <section class="dashboard-section">
        <div class="row dashboard-nowrap">
                <ul class="nav flex-column long-bg">
                        <li class="nav-item">
                            <a class="nav-link" href="/main/">
                                <span>Pulpit</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/recipe/list/">
                                <span>Przepisy</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/plan/list/">
                                <span>Plany</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <!-- Podstrony związane z zarządzaniem użytkownikami
                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <span>Edytuj dane</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="">
                                <span>Zmień hasło</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">
                                <span>Użytkownicy</span>
                                <i class="fas fa-angle-right"></i>
                            </a>
                        </li>
                        -->
                    </ul>

            <div class="m-4 p-3 width-medium text-color-darker">

<!-- //--------------------------- page content -------------------------// -->
{% block content %}{% endblock content %}
<!-- //--------------------------- page content end ---------------------// -->

            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

jedzonko/templates/about.html
{% extends "__base__.html" %}
{% block title %}o aplikacji{% endblock %}
{% block content %}


    <div class="dashboard-content border-dashed p-3 m-4 view-height">

        <div class="mt-4 ml-4 mr-4">
            <div class="row border-bottom border-3">
                <div class="col"><h3 class="color-header text-uppercase">o aplikacji</h3></div></div>

                {% if about_detail %}
                <div class="p-4">
                    {% for detail in about_detail %}
                        <p>{{ detail | linebreaks }}</p>
                    {% endfor %}
                {% endif %}
                </div>
    </div></div>

{% endblock content %}

jedzonko/templates/app-add-recipe.html
{% extends "__base__.html" %}

{% block title %}Nowy przepis{% endblock %}

{% block content %}
<form method="post">
<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="mt-4 ml-4 mr-4">
        <div class="row border-bottom border-3">
            <div class="col"><h3 class="color-header text-uppercase">Nowy
                przepis   </h3> </div>

            <div class="col d-flex justify-content-end mb-2">
                <button type="submit"
                        class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">
                    Zapisz
                </button>
            </div>
        </div>
        <div class="col"><h3 class="color-header text-uppercase"> <center><font color = red>{{ Info }} </font> </center>   </h3> </div>
        <table class="table borderless">
            <tbody>
            <tr class="d-flex">
                <th scope="row" class="col-2">Nazwa przepisu</th>
                <td class="col-7">
                    <input class="w-100 p-1" name = 'name' value="{{ name }}">
                </td>
            </tr>
            <tr class="d-flex">
                <th scope="row" class="col-2">Opis przepisu</th>
                <td class="col-7"><textarea class="w-100 p-1"
                                            rows="5" name="description">{{ description }}</textarea></td>
            </tr>
            <tr class="d-flex">
                <th scope="row" class="col-2">Przygotowanie (minuty)</th>
                <td class="col-3">
                    <input class="p-1" type="number" value="{{ preparation_time }}" name="preparation_time">
                </td>
            </tr>
            </tbody>
        </table>

        <div class="row d-flex">
            <div class="col-5 border-bottom border-3"><h3
                    class="text-uppercase">Sposób przygotowania</h3></div>
            <div class="col-2"></div>
            <div class="col-5 border-bottom border-3"><h3
                    class="text-uppercase">Składniki</h3></div>
        </div>
        <div class="row d-flex">
            <div class="col-5 p-4">
                <textarea class="w-100 p-1" name="preparation" rows="10">{{ preparation }}</textarea>
            </div>
            <div class="col-2"></div>

            <div class="col-5 p-4">
                <textarea class="w-100 p-1" name="ingredients" rows="10">{{ ingredients }}</textarea>
            </div>
        </div>
    </div>




</div>
{% csrf_token %}

</form>
{% endblock content %}

jedzonko/templates/app-add-schedules.html
{% extends "__base__.html" %}
{% block content %}
    <form action="" method="POST">
        <div class="dashboard-content border-dashed p-3 m-4 view-height">
            <div class="row border-bottom border-3 p-1 m-1">
                <div class="col noPadding">
                    <h3 class="color-header text-uppercase">NOWY PLAN</h3>
                </div>
                <div class="col d-flex justify-content-end mb-2 noPadding">
                    <button type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Zapisz</button>
                </div>
            </div>
<div class="col"><h3 class="color-header text-uppercase"> <center><font color = red>{{ Info }} </font> </center>   </h3> </div>
            <div class="schedules-content">
                <div class="form-group row">
                    <label for="planName"
                           class="col-sm-2 label-size col-form-label">
                        Nazwa planu
                    </label>

                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="planName"
                               placeholder="Nazwa planu" name="name">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="planDescription"
                           class="col-sm-2 label-size col-form-label">
                        Opis planu
                    </label>
                    <div class="col-sm-10">
                        <textarea class="form-control" rows="5" id="planDescription"
                                  placeholder="Opis planu" name="description"></textarea>
                    </div>
                </div>
            </div>
        </div>
        {% csrf_token %}
    </form>
{% endblock content %}
{% block title %}{% endblock %}

jedzonko/templates/app-details-schedules.html
{% extends "__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}
    <form method="post">
        <div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">SZCZEGÓŁY PLANU</h3>
        </div>
        <div class="col d-flex justify-content-end mb-2 noPadding">
            <a href="/plan/list/" class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">Powrót</a>
        </div>
    </div>
            <div class=" menu-item col justify-content-end mb-2 noPadding" >
            <a href="/plan/add-recipe/" style="color: #1e7e34">
                <i class="far fa-plus-square icon-plus-square"></i>
                <span class="title">dodaj przepis do planu</span>
            </a>
            </div>
    <div class="schedules-content">
        <div class="schedules-content-header">
            <div class="form-group row">
              
                                <span class="col-sm-2 label-size col-form-label">
                                    Nazwa planu
                                </span>
                        <div class="col-sm-10">
                            <p class="schedules-text"> {{ plan.name }}</p>
                        </div>
                    </div>
                    <div class="form-group row">
                                <span class="col-sm-2 label-size col-form-label">
                                    Opis planu
                                </span>
                        <div class="col-sm-10">
                            <p class="schedules-text">
                                {{ plan.description }}
                            </p>
                        </div>
                    </div>
                </div>

                {% for day in days %}
                    {% if day in plan.day_names.all %}
                        <table class="table">


                            <thead>
                            <tr class="d-flex">
                                <th class="col-2">{{ day.get_day_name_display }}</th>
                                <th class="col-7"></th>
                                <th class="col-1"></th>
                                <th class="col-2"></th>
                            </tr>
                            </thead>
                            <tbody class="text-color-lighter">
                            {% for meal in meals %}
                                {% if meal.day_name == day %}
                                    <tr class="d-flex">
                                    <td class="col-2">{{ meal.meal_name }}</td>
                                    <td class="col-7">{{ meal.recipe.name }}</td>
                                    <td class="col-1 center">
                                        <button class="btn btn-danger rounded-0 text-light m-1" name="delete_meal_id"
                                                type="submit" value="{{ meal.pk }}">Usuń
                                        </button>
                                    </td>
                                    <td class="col-2 center">
                                        <a href="/recipe/{{ meal.recipe.id }}/"
                                           class="btn btn-info rounded-0 text-light m-1">Szczegóły</a>
                                    </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        {% csrf_token %}
    </form>

{% endblock content %}

jedzonko/templates/app-edit-recipe.html
{% extends "__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}
    <form method="post">
        <div class="dashboard-content border-dashed p-3 m-4 view-height">

            <div class="mt-4 ml-4 mr-4">
                <div class="row border-bottom border-3">
                    <div class="col"><h3 class="color-header text-uppercase">Edycja
                        przepisu</h3></div>
                    <div class="col d-flex justify-content-end mb-2">
                        <button type="submit"
                                class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">
                            Wyślij
                        </button>
                    </div>
                </div>
                {% if messages %}
                    <div class="col">
                        {% for message in messages %}
                            <h3 class="color-header text-uppercase">
                                <center><font color=red>{{ message }}</font></center>
                            </h3>
                        {% endfor %}
                    </div>
                {% endif %}
                <table class="table borderless">
                    <tbody>
                    <tr class="d-flex">
                        <th scope="row" class="col-2">Nazwa Przepisu</th>
                        <td class="col-7">
                            <input class="w-100 p-1" name='name' value="{{ recipe.name }}">
                        </td>
                    </tr>
                    <tr class="d-flex">
                        <th scope="row" class="col-2">Opis przepisu</th>
                        <td class="col-7"><textarea class="w-100 p-1" rows="5"
                                                    name="description">{{ recipe.description }}</textarea>
                        </td>
                    </tr>
                    <tr class="d-flex">
                        <th scope="row" class="col-2">Przygotowanie (minuty)</th>
                        <td class="col-3">
                            <input class="p-1" type="number" name="preparation_time"
                                   value="{{ recipe.preparation_time }}">
                            <input type="hidden" name="id" value="{{ recipe.id }}">
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div class="row d-flex">
                    <div class="col-5 border-bottom border-3"><h3
                            class="text-uppercase">Sposób przygotowania</h3></div>
                    <div class="col-2"></div>
                    <div class="col-5 border-bottom border-3"><h3
                            class="text-uppercase">Składniki</h3></div>
                </div>
                <div class="row d-flex">
                    <div class="col-5 p-4">
                        <textarea class="w-100 p-1" rows="10" name="preparation">{{ recipe.preparation }}</textarea>
                    </div>
                    <div class="col-2"></div>

                    <div class="col-5 p-4">
                        <textarea class="w-100 p-1" rows="10" name="ingredients">{{ recipe.ingredients }}</textarea>
                    </div>
                </div>
            </div>
        </div>
        {% csrf_token %}
    </form>
{% endblock content %}

jedzonko/templates/app-edit-schedules.html
{% extends "__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}

    <div class="dashboard-content border-dashed p-3 m-4 view-height">
        <form method="post">
        <div class="row border-bottom border-3 p-1 m-1">
            <div class="col noPadding">
                <h3 class="color-header text-uppercase">Edycja planu</h3>
            </div>


             <div class="col d-flex justify-content-end mb-2">
             <button type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">
             Wyślij </button>
              </div>

        {% csrf_token %}
        </div>

        <div class="schedules-content">
            <form>
                <div class="form-group row">
                    <label for="planName"
                           class="col-sm-2 label-size col-form-label">
                        Nazwa planu
                    </label>
                    <div class="col-sm-10">
                        <input class="form-control"
                               value= "{{ plan.name }}" name="name"
                               id="planName" placeholder="Nazwa planu">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="planDescription"
                           class="col-sm-2 label-size col-form-label">
                        Opis planu
                    </label>
                    <div class="col-sm-10">
                                        <textarea name="description" class="form-control" rows="5"
                                                  id="planDescription"
                                                  placeholder="Opis plany"> {{ plan.description }}</textarea>
                    </div>
                </div>
            </form>
        </div>

        </form>
    </div>

{% endblock content %}